---
abstract: 'REST integration with icinga2'
author:
  - 'Johan Wassberg <jocar@su.se>'
  - 'Mikael Nordin <mikael.nordin@su.se'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Monitoring-Icinga2-Client-REST
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Encode: '0'
  ExtUtils::MakeMaker: '0'
  HTTP::Request: '0'
  JSON: '0'
  LWP::UserAgent: '0'
  Scalar::Util: '0'
  URI::Escape: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: http://github.com/stockholmuniversity/SU-API-Icinga2-perl/issues
  homepage: https://github.com/stockholmuniversity/SU-API-Icinga2-perl
  license: http://dev.perl.org/licenses/
version: 2.0.4
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
